---
title: "Weather_datathon"
author: "Erick onyango ooko"
date: "2024-03-15"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
# Load the dataset
library(readxl)
weather_data <- read_excel("C:/Users/admin/Downloads/weather data.xlsx")

View(weather_data)
```

## Temperature trends over time

```{r}
library(ggplot2)

ggplot(weather_data, aes(x = as.POSIXct(`Date/Time`, format = "%m/%d/%Y %H:%M"), y = Temp_C)) +
  geom_line() +
  xlab("Date/Time") +
  ylab("Temperature (C)") 
```

## Analyze the relationship between wind speed and temperature

```{r}
ggplot(weather_data, aes(x = `Wind Speed_km/h`, y = Temp_C)) +
  geom_point() +
  xlab("Wind Speed (km/h)") +
  ylab("Temperature (C)") 

correlation <- cor(weather_data$`Wind Speed_km/h`, weather_data$Temp_C)
correlation
```

## Forecasting temperature using ARIMA

```{r}
library(forecast)

# Assuming the temperature data is in a column named "Temp_C"
temperature <- ts(weather_data$Temp_C)

# Fit ARIMA model
model <- auto.arima(temperature)

# Forecast next 10 time points
forecast <- forecast(model, h = 10)

# Plot the forecast
plot(forecast, main="")
```

## Detecting outliers or anomalies

```{r}
boxplot(weather_data$Temp_C, main = "")
```
## Decompose the data

```{r}
library(stats)
# Convert 'Years' column to a date format
weather_data$`Date/Time` = as.POSIXct(weather_data$`Date/Time`, format = "%m/%d/%Y %H:%M")


# Remove rows with null values
clean_data <- weather_data[complete.cases(weather_data), ]
weather_data = clean_data

# Convert the data to a time series object
ts_data <- ts(weather_data$Temp_C, frequency = 6, start = c(min(weather_data$`Date/Time`)))

#decompose the ts
decomposed_data<-decompose(ts_data)

plot(decomposed_data)
```
## Calculate the correlation matrix

```{r}
# Select only the numeric columns
numeric_columns <- weather_data[, sapply(weather_data, is.numeric)]

# Calculate the correlation matrix for numeric columns
cor_matrix <- cor(numeric_columns)

# Print the correlation matrix
print(cor_matrix)


library(ggplot2)

# Convert correlation matrix to long format
cor_df <- reshape2::melt(cor_matrix)

# Plot the heatmap using ggplot2
ggplot(data = cor_df, aes(x = Var2, y = Var1, fill = value)) +
  geom_tile() +
  scale_fill_gradient2(low = "blue", mid = "white", high = "red", midpoint = 0) +
  labs(title = "Correlation Heatmap", x = "Variables", y = "Variables") +
  theme_minimal()

# Add color legend
heat_colors <- c("blue", "white", "red")
breaks <- seq(-1, 1, by = 0.2)
labels <- c("Low Correlation", "", "", "", "", "High Correlation")


```

